name: Test

on: [push, pull_request]

jobs:
  test:
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up node
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
